# Generated by Django 4.0.2 on 2022-02-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_wage_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founded', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shirt_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
