# Generated by Django 4.0.2 on 2022-02-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_player_name_player_shirt_number_player_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='wage',
            name='player',
        ),
    ]
