# Generated by Django 4.0.2 on 2022-02-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_remove_player_team_remove_wage_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='team.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='team.player'),
            preserve_default=False,
        ),
    ]
