# Generated by Django 4.0.2 on 2022-02-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_player_team_wage_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='currency',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wage',
            name='wage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
