# Generated by Django 4.0.2 on 2022-04-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_remove_exchangerate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
