# Generated by Django 4.0.2 on 2022-06-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_alter_exchangerate_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='team.player'),
            preserve_default=False,
        ),
    ]
