# Generated by Django 4.0.2 on 2022-02-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='away',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home',
        ),
        migrations.RemoveField(
            model_name='game',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='game',
            name='stadium',
        ),
    ]
