# Generated by Django 4.0.2 on 2022-02-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_game_away_game_home_game_referee_game_stadium'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefereeFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='stadium',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='referee',
            name='function',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='league.refereefunction'),
            preserve_default=False,
        ),
    ]
