# Generated by Django 4.0.2 on 2022-03-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
