# Generated by Django 4.0.2 on 2022-03-23 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_league_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='courseofthegame',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='league.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='number',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='post_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='street',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
